# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # Liste des filter set (ensemble de filtres) de l’application
    filter_sets:
        cache: ~
        user_mini_thumbnail:

            # il existe de nombreux filtres prédéfinis (http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html) mais il est aussi possible d’en créer.
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [52, 52], mode: outbound }
        user_thumbnail:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [100, 100], mode: outbound }
