# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # Liste des filter set (ensemble de filtres) de l’application
    filter_sets:
        cache: ~
        user_mini_thumbnail:
            # il existe de nombreux filtres prédéfinis (http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html) mais il est aussi possible d’en créer.
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [250, 250], mode: outbound }
        user_thumbnail:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [100, 100], mode: outbound }

        # name our filter set "my_crop_filter"
        my_crop_filter:
            filters:
                # use and setup the "crop" filter
                crop:
                    # set the size of the cropping area
                    size: [ 1300, 500 ]
                    # set the starting coordinates of the crop
                    start: [ 0, 0 ]
        # name our first filter set "my_heighten_filter"
        my_heighten_filter:
            filters:

                # use and setup the "relative_resize" filter
                relative_resize:

                    # given 50x40px, output 75x60px using "heighten" option
                    heighten: 500
